"""Adds active attribute for flask login and security

Revision ID: 09857774d369
Revises: 34715bbe2d06
Create Date: 2024-08-06 23:13:19.197114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09857774d369'
down_revision = '34715bbe2d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
