"""Fixes dunder typo

Revision ID: cdcca2ac4d59
Revises: 09857774d369
Create Date: 2024-08-07 09:55:42.347242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcca2ac4d59'
down_revision = '09857774d369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint('parcels_tracking_number_key', type_='unique')
        batch_op.drop_column('tracking_number')

    with op.batch_alter_table('recipient_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipient_addresses_recipient_id_recipients'), 'recipients', ['recipient_id'], ['id'])

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipients_parcel_id_parcels'), 'parcels', ['parcel_id'], ['id'])

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_addresses_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_addresses_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipients_parcel_id_parcels'), type_='foreignkey')
        batch_op.drop_column('parcel_id')

    with op.batch_alter_table('recipient_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipient_addresses_recipient_id_recipients'), type_='foreignkey')
        batch_op.drop_column('recipient_id')

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('parcels_tracking_number_key', ['tracking_number'])

    # ### end Alembic commands ###
